- README.md
partially addresses #20 . This PR removes all the "ideas for things that should get done" from the README. It's more appropriate to do planning in Issues, not in random bullet points in a README
> Moved issues out of README

- .codecov.yml
- doppel/bin/analyze.R
- doppel/bin/analyze.py
- doppel/cli.py
- doppel/reporters.py
This PR added the ability to compare the set of public methods implemented in different classes. It will provided errors like this:
```
1. Not all implementations of class 'Whatever' have public method 'do_stuff()
```
It also adds analysis of the args to each method, but not comparisons on them.
> Added ability to compare class methods

- doppel/bin/analyze.R
- doppel/bin/analyze.py
- doppel/describe.py
As of this PR, class constructors will now show up in the list of public methods! Because the constructors for classes can be different across languages, I added a `--constructor-string` argument similar to the way "pass through kwargs" differences were handled.
For example, in Python the constructor is called `__init__()` and in R6 (R) it is `initialize()`
> added constructors to list of public methods (fixes #61)

- doppel/bin/analyze.py
This PR fixes a bug in the way `analyze.py` handles listing out the public methods on classes. See #78  for full details, but basically checking "is it a function" is a better way to tell if something is a function than "is it callable" (yes, I know, seems obvious now that I type it).
> changed parsing strategy for class members in python (fixes #78)

- .codecov.yml
- tests/test_DoppelTestError.py
- tests/test_reporters.py
this PR introduces two smoke tests on SimpleReporter to get a quick boost in code coverage. These tests aren't capturing functional correctness, but by covering so much code they do catch annoying things like type mismatches.
> add some basic unit tests on SimpleReporter (fixes #53, fixes #54)

- README.md
- doppel/reporters.py
- tests/test_reporters.py
This PR fixes #59 , adding checks on the order of keyword arguments in public methods. This is the last major change needed for release 2.0!
> Public method order (fixes #59)

- doppel/PackageCollection.py
- tests/test_package_collection.py
- tests/test_reporters.py
Hopefully no one will ever actually hit this error. But having this check in `PackageCollection` will prevent other things from silently making it through.
> Added uniqueness constraint on names in PackageCollection (fixes #88)

- .gitignore
- CONTRIBUTING.md
- NEWS.md
- README.md
- doppel/bin/analyze.py
- smoke_tests/all_r_packages.sh
- smoke_tests/python_packages
- smoke_tests/r_packages
- smoke_tests/run.sh
This PR is a work in progress and still needs some love. It tries to introduce some smoke tests that can be run by developers on their laptops to see if `doppel-cli` still works for a bunch of R and Python packages.
> Smoke tests (fixes #80)

- .ci/setup.sh
- .ci/test-analyze-r-coverage.R
- .ci/test-analyze-r.R
- .ci/test.sh
- NEWS.md
- doppel/bin/analyze.R
- integration_tests/test-packages/r/testpkguno/DESCRIPTION
In this PR, I had to jump through some hoops to compute code coverage of `analyze.R`. But I think I figured it out!
The diff is hard to read, but basically the code in `analyze.R` had to be wrapped in a function to make it usable by `covr`.
Happy to report that 95% of the code in `analyze.R` is covered by existing tests!
> Added code coverage on analyze.R (fixes #55)

- doppel/bin/analyze.py
- integration_tests/test-packages/python/testpkguno/testpkguno/ClassA.py
This is a fix to include keyword-only arguments in the arguments that doppel finds for python signatures.
> Added keyword-only arguments to function signatures (fixes #125)

- .ci/setup.sh
- .ci/test-analyze-r-coverage.R
- .ci/test-analyze-r.R
`r-base` is a somewhat heavy dependency. I noticed a lot of unnecessary stuff like `rstudioapi` getting installed. Trying, in this PR, to pare down this project's CI to the absolute minimum dependencies
> tried to speed up R installs (fixes #139)

- README.md
This PR addresses two issues when trying to follow the README to run doppel for the first time:
1. The R packages used by the R script are not explicitly installed anywhere or checked for, except when running the script, which will error out. 
2. The example writes the output files to a directory called `test_data`, which will error out if that directory does not already exist.
> Add R requirements and mkdir to README

- .ci/setup.sh
- setup.py
This should fix issue #142 . 
Simply removing the whole install.packages() line resulted in an error related to argparse not being recognised. I thus added this item to the conda install after removing the install.packages() line. 
This has resulted in a roughly 30s decrease in run time for each individual Travis build job, with ~1.5min decrease in the aggregated build run time, and ~2.5min decrease in the total time.
Let me know if you need any edits!
> removed duplicate R installs from setup.sh (fixes #142)

- doppel/bin/analyze.py
- integration_tests/python_tests/test_analyze.py
- integration_tests/test-packages/python/pythonspecific/pythonspecific/mod_two/GreatClass.py
This PR adds tests that I forgot to commit and push on #143 . It takes the test coverage on `analyze.py` from 92% to 93%.
This is in pursuit of #135
Coverage results as of this PR:
```
---------- coverage: platform darwin, python 3.6.7-final-0 -----------
Name                Stmts   Miss  Cover
---------------------------------------
doppel_analyze.py     119      8    93%
=========================== 1 passed in 0.07 seconds ===========================
Name                Stmts   Miss  Cover   Missing
-------------------------------------------------
doppel_analyze.py     119      8    93%   74, 204-209, 253, 273-274
```
> Add more tests on analyze.py

- .ci/test.sh
- doppel/bin/analyze.py
- integration_tests/python_tests/test_analyze.py
- integration_tests/test-packages/python/pythonspecific/pythonspecific/mod_one/__init__.py
- integration_tests/test-packages/python/pythonspecific/pythonspecific/mod_one/wrap_min.py
- integration_tests/test-packages/r/testpkgdos/DESCRIPTION
- integration_tests/test-packages/r/testpkgtres/DESCRIPTION
- integration_tests/test-packages/r/testpkguno/DESCRIPTION
The tests in this PR take us to 98% coverage of `analyze.py`! It also fixes a bug in the tests, where tests on `pythonspecific` were not actually being run because the test class's name didn't start with `Test`.
```
platform darwin -- Python 3.6.7, pytest-5.0.1, py-1.5.4, pluggy-0.12.0
rootdir: /Users/jlamb/repos/doppel-cli
plugins: cov-2.7.1
collected 1 item
test_analyze_py.py .                                                     [100%]
---------- coverage: platform darwin, python 3.6.7-final-0 -----------
Name                Stmts   Miss  Cover
---------------------------------------
doppel_analyze.py     126      3    98%
=========================== 1 passed in 0.09 seconds ===========================
Name                Stmts   Miss  Cover   Missing …
```
> [ci] added tests on analyze.py handling of Python built-ins

- .ci/test.sh
- doppel/bin/analyze.py
- doppel/reporters.py
- integration_tests/test-packages/python/pythonspecific/pythonspecific/__init__.py
- integration_tests/test-packages/python/pythonspecific/pythonspecific/mod_three/__init__.py
- tests/test_reporters.py
This PR introduces some code to the test package `pythonspecific` to cover the branch in `analyze.py` that avoids parsing a module that has already been parsed. This is a real scenario that I've observed in packages like `pandas`.
The code being covered by these tests was introduced in #120, see there for more.
> [ci] Added tests on re-use of modules in Python (fixes #135)

- .ci/setup.sh
- .gitignore
- .travis.yml
- doppel/bin/analyze.py
- integration_tests/python_tests/test_analyze.py
- integration_tests/test-packages/python/pythonspecific2/pythonspecific2/__init__.py
- integration_tests/test-packages/python/pythonspecific2/pythonspecific2/module.py
- integration_tests/test-packages/python/pythonspecific2/setup.py
In this PR, I attempted to fix the issue @austin3dickey raised in #160 . The fix here returns `doppel-cli`'s handling of standard-lib functions (e.g. `from warnings import warn`)  to the previous behavior.
I added @austin3dickey's reproducible example as a test package and added tests on it. Note that in those tests, I'm not taking a stand on what the behavior _should_ be, just trying to document the current behavior so regressions like this aren't accidentally introduced in the future.
For example, right now I know that `doppel-cli` isn't doing the "right" thing for a package like `feather`, where it seems obvious that [they are trying to "re-export" from other packages](https://github.com/wesm/feather/blob/master/python/feather/api.py#L15)
```python
from pyarrow.feather import …
```
> Fixed regression in handling of imports (fixes #160)

- .ci/analyze_py_tests/test_analyze_py.py
- .ci/lint-py.sh
- .ci/setup.sh
- doppel/__init__.py
- doppel/bin/analyze.py
- doppel/cli.py
- doppel/reporters.py
- integration_tests/python_tests/test_analyze.py
- integration_tests/test-packages/python/pythonspecific/pythonspecific/__init__.py
- integration_tests/test-packages/python/pythonspecific/pythonspecific/mod_one/__init__.py
- integration_tests/test-packages/python/pythonspecific/pythonspecific/mod_three/__init__.py
- integration_tests/test-packages/python/pythonspecific2/pythonspecific2/__init__.py
- integration_tests/test-packages/python/pythonspecific2/pythonspecific2/module.py
- integration_tests/test-packages/python/testpkgdos/testpkgdos/__init__.py
- integration_tests/test-packages/python/testpkgtres/testpkgtres/__init__.py
- integration_tests/test-packages/python/testpkguno/testpkguno/__init__.py
- tests/test_DoppelTestError.py
This PR adds `flake8` linting, which caught some things that weren't caught by `pycodestyle`. It also fixes those things.
I added `# noqa` on all the test package  `__init__`  files. Those are intentionally set up the way they are so that they mimic behavior I've seen in other packages that might be tested with `doppel-cli`.
> [ci] adding flake8

- .appveyor.yml
Right now two AppVeyor builds are happening on every pull request...a `/branch` and a `/pr`.  This changes that. Now one `/pr` build will happen on every commit to a pull request, and one `/branch` build on new commits to master.
> [ci] fix duplicate AppVeyor builds

- doppel/cli.py
- doppel/describe.py
- integration_tests/python_tests/test_analyze.py
- integration_tests/test-packages/r/testpkgdos/DESCRIPTION
- integration_tests/test-packages/r/testpkgtres/DESCRIPTION
- integration_tests/test-packages/r/testpkguno/DESCRIPTION
Right now all CLI options (both in `doppel-describe` and `doppel-test`) are  just that..."options". Some of them are absolutely necessary for `doppel-cli`, but today  you only find that out by getting weird downstream errors.
This PR fixes  that.
> made required things required (fixes #168)

- .gitignore
- integration_tests/test-packages/r/testpkgdos/DESCRIPTION
- integration_tests/test-packages/r/testpkgtres/DESCRIPTION
- integration_tests/test-packages/r/testpkgtres/R/SomeClass.R
- integration_tests/test-packages/r/testpkguno/DESCRIPTION
- integration_tests/test-packages/r/testpkguno/R/ClassA.R
- integration_tests/test-packages/r/testpkguno/R/ClassB.R
- integration_tests/test-packages/r/testpkguno/R/ClassC.R
- integration_tests/test-packages/r/testpkguno/R/ClassD.R
- integration_tests/test-packages/r/testpkguno/R/ClassE.R
See #153 . This doesn't change `doppel-cli`'s functionality, but removes some warnings from the logs in CI.
> document R6 stuff (fixes #153)

- .ci/test.sh
- Makefile
- doppel/describe.py
- integration_tests/test-packages/python/pythonspecific2/setup.py
`black` recently did a new release. This PR reformats this project's code per that new release.
It also introduces a `Makefile` so you can just do `make format` (to format the code) and `make lint` (to run the linter) without needing to know about the shell scripts.
> [ci] updates for new version of black

- .github/workflows/ci.yml
- doppel/PackageAPI.py
This also upgrades to the latest version of the `conda-incubator/setup-miniconda` action.
> use more specific type hints

- docs/conf.py
- doppel/DoppelTestError.py
- doppel/PackageAPI.py
- doppel/bin/analyze.py
- doppel/cli.py
- doppel/describe.py
- doppel/reporters.py
- integration_tests/python_tests/test_analyze.py
- tests/test_package_api.py
- tests/test_package_collection.py
- tests/test_reporters.py
Fixes #204.
This small PR was made to change `{ }.format(a)` to f-strings, `f"( {a} )"`.
> use f-strings for string formatting (fixes #204)

- .github/workflows/ci.yml
- .github/workflows/publish-to-pypi.yml
- setup.py
Updates minimum Python version to `>=3.8`.
Updates all CI jobs to more recent versions of Python, to match.
> move Python version floor to v3.8

- .ci/lint-py.sh
- .ci/test.sh
This project already runs `flake8`.
https://github.com/jameslamb/doppel-cli/blob/0421564357ddad1bac651826e95c21ab5659ab82/.ci/lint-py.sh#L37-L40
which enforces all of the `pycodestyle` checks
https://flake8.pycqa.org/en/2.6.0/
so installing `pycodestyle` separately and running it separately are unnecessary.
> [ci] remove separate 'pycodestyle' step

- .ci/run-unit-tests.sh
- setup.py
Removes the following from `setup.py`:
* `[all]`, `[docs]`, `[testing]` optional dependencies
* `tests_require` + `test_suite`
It's not necessary to support stuff like `pip install 'doppel-cli[docs]'` in this project.
`setuptools` is going to drop support for directly invoking `setup.py` soon: https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html
> remove unnecessary other dependency lists in setup.py
